# Questions & Answers from Tech Interviews: from beginners to advance

This would be a collection of interviews requests about Python questions. This reference will be always mentioned for each question and the solution is given by myself (I always recommend to check your own solution and to give a look at the amazing references I used to take questions)

References:
- [1] 140+ Basic Python Programs from Piush Kumar Sharma
- [2] [Youtube playlist](https://www.youtube.com/watch?v=KDoC6oHaTek&list=PL_46-JrHsoaa8hpVKwMv6UGqRBh939Dgx)

## Easy

### Write a Python program to swap two variables [1]

In [ ]:
# Solution 1

class Solution(object):
    def swap_variables(self, var_a, var_b):
        """
        :var_a: int
        :var_b: int
        """
        

        print(f"- Original variable a: {var_a} \n- Original variable b: {var_b}")

        temporary_variable = var_a
        var_a = var_b
        var_b = temporary_variable

        print("="*30)
        print(f"- Swapped variable a: {var_a} \n- Swapped variable b: {var_b}")


variable_a = int(input("Enter first variable: "))
variable_b = int(input("Enter first variable: "))
my_solution = Solution()
my_solution.swap_variables(variable_a, variable_b)

- Original variable a: 5 
- Original variable b: 4
- Swapped variable a: 4 
- Swapped variable b: 5


In [ ]:
# Solution 2

class Solution(object):
    def swap_variables(self, var_a, var_b):
        """
        :var_a: int
        :var_b: int
        """
        

        print(f"- Original variable a: {var_a} \n- Original variable b: {var_b}")

        var_a, var_b = var_b, var_a

        print("="*30)
        print(f"- Swapped variable a: {var_a} \n- Swapped variable b: {var_b}")

variable_a = int(input("Enter first variable: "))
variable_b = int(input("Enter first variable: "))
my_solution = Solution()
my_solution.swap_variables(variable_a, variable_b)

- Original variable a: 10 
- Original variable b: 0
- Swapped variable a: 0 
- Swapped variable b: 10


### Write a Python program to generate a random number [1]

In [ ]:
# Solution 1 

import random

print(f"Random integer from 0 to 1000: {random.randint(0,1000)}")

Random integer from 0 to 1000: 292


In [11]:
# Solution 2

import numpy as np

print(f"Random integer from 0 to 1000: {np.random.randint(0,1000, size=1)[0]}")

Random integer from 0 to 1000: 364


### Write a Python program to display calendar [1]

In [23]:
import calendar

class Solution(object):
    def show_calendar(self, y, m):
        """
        :y: int
        :m: int
        """

        print(calendar.month(y, m))

year_var = int(input("Enter the year: "))
month_var = int(input("Enter the month: "))
my_solution = Solution()
my_solution.show_calendar(year_var, month_var)

      May 1994
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30 31



### Write a Python Program to Check if a Number is Odd or Even [1]

In [ ]:
class Solution(object):
    def evan_or_odd(self, num):
        """
        :num: int
        """

        print(f"Choosen number = {num}")
        if (num + 1)%2 == 0:
            print(f"{num} is odd")
        else:
            print(f"{num} is even")

number_var = int(input("Enter a number: "))
my_solution = Solution()
my_solution.evan_or_odd(number_var)

Choosen number = 10
10 is even


### Write a Python Program to Check Leap Year [1]

In [42]:
class Solution(object):
    def leap_year(self, y):
        """
        :y: int
        """
        return (y%4==0 and y%100 != 0) or (y%400 == 0)
    
year = int(input("Enter a year: "))
my_solution = Solution()
if my_solution.leap_year(year):
    print(f"{year} is leap.")
else:
    print(f"{year} is not leap.")

2016 is leap.


### Write a Python Program to Check Prime Number [1]

In [47]:
class Solution(object):
    def is_prime(self, num):
        """
        :num: int
        """

        if num <= 1:
            return False
        else:
            for i in range(2, num):
                if (num % i) == 0:
                    return False
            return True
        
number = int(input("Enter a number: "))
my_solution = Solution()
if my_solution.is_prime(number):
    print(f"{number} is prime.")
else:
    print(f"{number} is not prime.")          

13 is prime.


### Write a Python Program to Print all Prime Numbers in an Interval of 1-10 [1]

In [ ]:
class Solution(object):
    def is_prime(self, num):
        """
        :num: int
        """

        if num <= 1:
            return False
        else:
            for i in range(2, num):
                if (num % i) == 0:
                    return False
            return True
        
    def n_prime(self, min_num, max_num):
        """
        :min_num: int
        :max_num: int
        """
        for i in range(min_num, max_num):
            if self.is_prime(i):
                print(i)

lower = int(input("Enter a lower number of the interval: "))
upper = int(input("Enter a upper number of the interval: "))
my_solution = Solution()
print("Prime numbers between", lower, "and", upper, "are:")
my_solution.n_prime(lower, upper)

Prime numbers between 2 and 50 are:
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47


### Write a Python Program to Find the Factorial of a Number [1]

In [ ]:
# Solution 1 - Iteration

class Solution(object):
    def factorial_n(self, num):
        """
        :num: int
        """
        if num < 0:
            print("Number should be greater than 0")
        elif num == 0 or num == 1:
            print(f"Factorial of {num} is 1")
        else:
            fact = 1
            for i in range(2, num+1):
                fact = fact * i
            print(f"Factorial of {num} is {fact}")

number = int(input("Enter a number: "))
my_solution = Solution()
my_solution.factorial_n(number)

Factorial of 7 is 5040


In [9]:
# Solution 2 - Recursion

class Solution(object):
    def factorial_n(self, num):
        """
        :num: int
        """
        if num < 0:
            print("Number should be greater than 0")
        elif num == 0 or num == 1:
            return 1
        else:
            return num * self.factorial_n(num-1)

number = int(input("Enter a number: "))
my_solution = Solution()
print(f"Factorial of {number} is {my_solution.factorial_n(number)}")

Factorial of 7 is 5040


### Write a Python Program to Print the Fibonacci sequence [1]

In [61]:
# Solution 1 - Iterative method

class Solution(object):
    def fibonacci_seq(self, num):
        """
        :num: int
        """
        if num < 0:
            print("Number should be greater than 0")
        elif num == 0:
            return num
        elif num == 1:
            return [num-1, num]
        else:
            seq = [0,1]
            for i in range(2, num):
                seq.append(seq[-1] + seq[-2])
            return seq

number = int(input("Enter a number: "))
my_solution = Solution()
my_solution.fibonacci_seq(number)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [ ]:
# Solution 2 - Recursive method

class Solution(object):
    def fibonacci_seq(self, num):
        """
        :num: int
        """
        if num < 0:
            print("Number should be greater than 0")
        elif num <= 1:
            return num
        else:
            return self.fibonacci_seq(num-1) + self.fibonacci_seq(num-2)

number = int(input("Enter a number: "))
my_solution = Solution()
print(f"Fibonacci sequence up to {number}: {[my_solution.fibonacci_seq(n) for n in range(0, number)]}")

Fibonacci sequence up to 10: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


### Write a Python Program to Find the Sum of Natural Numbers [1]

In [70]:
class Solution(object):
    def sum_natural(self, num):
        """
        :num: int
        """
        sum = 0
        if num <= 0:
            print("Number should be greater than 0")
        for i in range(0,num+1):
            sum += i
        return sum

number = int(input("Enter a number: "))
my_solution = Solution()
print(f"Sum of first {number} natural numbers: {my_solution.sum_natural(number)}")

Sum of first 10 natural numbers: 55


### Write a Python Program to Find LCM [1]

In [80]:
class Solution(object):
    def lcm(self, num_1, num_2):
        """
        :num_1: int
        :num_2: int
        """
        if num_1 < 0 or num_2 < 0:
            print("You need positive numbers")
            return None

        maximum = max(num_1, num_2)

        while True:
            if maximum%num_1==0 and maximum%num_2==0:
                return maximum
            maximum += 1

number_1 = int(input("Enter a number: "))
number_2 = int(input("Enter a number: "))
my_solution = Solution()
print(f"Least Common Multiple for {number_1, number_2}: {my_solution.lcm(number_1, number_2)}")

Least Common Multiple for (10, 100): 100


In [ ]:
# I found out that maybe there is a more efficient solution with the GCD formula

class Solution(object):
    def gdc(self, a, b):
        minimum = min(a, b)
        while True:
            if a % minimum == 0 and b % minimum == 0:
                return minimum
            minimum -= 1

    def lcm(self, num_1, num_2):
        """
        :num_1: int
        :num_2: int
        """
        if num_1 < 0 or num_2 < 0:
            print("You need positive numbers")
            return None
        
        return abs(num_1*num_2) // self.gdc(num_1, num_2)

number_1 = int(input("Enter a number: "))
number_2 = int(input("Enter a number: "))
my_solution = Solution()
print(f"Least Common Multiple for {number_1, number_2}: {my_solution.lcm(number_1, number_2)}")

Least Common Multiple for (4, 12): 12


### Write a Python Program to Convert Decimal to Binary, Octal and Hexadecimal [1]

In [100]:
class Solution(object):
    def number_conversion(self, num, f):
        """
        :num: int
        :f: str
        """
        if f.lower() == 'binary':
            return bin(num)
        elif f.lower() == 'octal':
            return oct(num)
        elif f.lower() == 'hexadecimal':
            return hex(num)
        else:
            print("Incorrect format!")
        
number = int(input("Enter a number: "))
format = input("Enter a format: ")
my_solution = Solution()
print(f"Conversion of {number} in {format.capitalize()}: {my_solution.number_conversion(number, format)}")

Conversion of 4 in Octal: 0o4


### Write a Python Program To Find ASCII value of a character [1]

In [7]:
class Solution(object):
    def ascii_car(self, char):
        """
        :char: str
        """
        if len(char) > 1:
            print("You need only one character!")
            return None
        return ord(char)
        
character = str(input("Enter a character: "))
my_solution = Solution()
print(f"Conversion of {character} in ASCII: {my_solution.ascii_car(character)}")

Conversion of P in ASCII: 80


### Write a Python Program to Split the array and add the first part to the end [1]

In [ ]:
class Solution(object):
    def rotate_array(self, arr, pos):
        """
        :arr: List[int]
        :pos: int
        """
        dim = len(arr)
        if pos < 0 or pos > dim:
            return f"Error! You need a position greater than 0 or less than array length {dim}"
        return arr[pos:] + arr[:pos]
        
array = [1,2,3,4,5,6,7,8,9]
position = 5
my_solution = Solution()
print("Original Array:", array)
print("Rotated Array:", my_solution.rotate_array(array, position))

Original Array: [1, 2, 3, 4, 5, 6, 7, 8, 9]
Rotated Array: [6, 7, 8, 9, 1, 2, 3, 4, 5]


### Write a Python Program to check if given array is Monotonic [1]

In [22]:
class Solution(object):
    def is_monotonic(self, arr):
        """
        :arr: List[int]
        """
        increasing = decreasing = True

        for i in range(1, len(arr)):
            if arr[i] > arr[i-1]:
                decreasing = False
            if arr[i] < arr[i-1]:
                increasing = False
        
        return increasing or decreasing
        
array = [1,2,3,4,5,6,7,11,9]
my_solution = Solution()
print("Is Array Monotonic:", my_solution.is_monotonic(array))

Is Array Monotonic: False


### Write a Python Program to Add Two Matrices [1]

In [38]:
class Solution(object):
    def sum_matrices(self, mat_1, mat_2):
        """
        :mat_1: List
        :mat_2: List
        """

        if len(mat_1) != len(mat_2) or len(mat_1[0]) != len(mat_2[0]):
            return f"Error! Matrices should have the same dimensions: ({len(mat_1)},{len(mat_1[0])}) ({len(mat_2)},{len(mat_2[0])})"
        
        matrix_sum = [] 
        for i in range(0, len(mat_1)):
            row = []
            for j in range(0, len(mat_1[0])):
                row.append(mat_1[i][j] + mat_2[i][j])
            matrix_sum.append(row)
        
        return matrix_sum
    
matrix1 = [
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
]
matrix2 = [
[9, 8, 7],
[6, 5, 4],
[3, 2, 1]
]

my_solution = Solution()
print(f"Matrix sum:\n{my_solution.sum_matrices(matrix1,matrix2)}")

Matrix sum:
[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


### Write a Python Program to Multiply Two Matrices [1]

In [44]:
class Solution(object):
    def multiply_matrices(self, mat_1, mat_2):
        """
        :mat_1: List
        :mat_2: List
        """

        rows_1, cols_1 = len(mat_1), len(mat_1[0])
        rows_2, cols_2 = len(mat_2), len(mat_2[0])

        if cols_1 != rows_2:
            raise ValueError(f"Number of columns in A should be equal to the number of rows in B. ({rows_1},{cols_1}) != ({rows_2}, {cols_2})")
        
        matrix_prod = [[0 for _ in range(cols_2)] for _ in range(rows_1)]
        for i in range(0, rows_1):
            for j in range(0, cols_2):
                for k in range(0, cols_1):
                    matrix_prod[i][j] += mat_1[i][k] * mat_2[k][j]
        return matrix_prod
    
matrix1 = [
[1, 2, 3],
[4, 5, 6]
]
matrix2 = [
[9, 8, 7, 8],
[6, 5, 4, 8],
[3, 2, 1, 9]
]

my_solution = Solution()
print(f"Matrix prod:\n{my_solution.multiply_matrices(matrix1,matrix2)}")

Matrix prod:
[[30, 24, 18, 51], [84, 69, 54, 126]]


In [ ]:
# If you need to check with Numpy

import numpy as np

np.matrix(matrix1)*np.matrix(matrix2)

matrix([[ 30,  24,  18,  51],
        [ 84,  69,  54, 126]])

### Write a Python Program to Transpose a Matrix [1]

In [46]:
class Solution(object):
    def transpose_matrix(self, mat):
        """
        :mat_1: List
        """

        rows, cols = len(mat), len(mat[0])

        mat_transpose = [[0 for _ in range(rows)] for _ in range(cols)]     
        for i in range(0, rows):
            for j in range(0, cols):
                    mat_transpose[j][i] = mat[i][j]
        return mat_transpose
    
matrix = [
[1, 2, 3],
[4, 5, 6]
]

my_solution = Solution()
print(f"Matrix transpose:\n{my_solution.transpose_matrix(matrix)}")

Matrix transpose:
[[1, 4], [2, 5], [3, 6]]


### Write a Python Program to Sort Words in Alphabetic Order [1]

In [ ]:
class Solution(object):
    def alphabetic_sort(self, sent):
        """
        :sent: string
        """
        return sorted([word.lower() for word in sent.split(" ")])
    
sentence = str(input("Enter a sentence: "))

my_solution = Solution()
print(f"Sentence: {sentence}")
print(f"Sorted words:\n")
words = my_solution.alphabetic_sort(sentence)
for i in range(len(words)):
    print(f"{i+1}. {words[i].capitalize()}")

Sentence: sdsad ewerew xv qewe oico bbv saa Aa
Sorted words:

1. Aa
2. Bbv
3. Ewerew
4. Oico
5. Qewe
6. Saa
7. Sdsad
8. Xv


### Write a Python Program to Remove Punctuation From a String [1]

In [59]:
class Solution(object):
    def remove_punctuation(self, sent):
        """
        :sent: string
        """
        punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
        for character in punctuations:
            sent = sent.replace(f"{character}", "")
        return sent
    
sentence = str(input("Enter a sentence: "))

my_solution = Solution()
print(f"Sentence: {sentence}")
print(f"Sentence without punctuation:")
print(f"{my_solution.remove_punctuation(sentence)}")

Sentence: ciao sono Silvano, vivo a Barletta e parlo Italiano!!
Sentence without punctuation:
ciao sono Silvano vivo a Barletta e parlo Italiano


### Write a Python program to check if the given number is a Disarium Number [1]

8<sup>1</sup> + 9<sup>2</sup> = 8 + 81 = 89

In [ ]:
class Solution(object):
    def is_disarium(self, num):
        """
        :num: int
        """

        if num < 0:
            raise(ValueError(f"Number should be greater than 0 and not {num}"))

        str_num = str(num)
        squared_digits_sum = 0
        for (i,digit) in enumerate(str_num):
            squared_digits_sum += pow(int(digit),i+1)
        return squared_digits_sum == num
    
number = int(input("Enter a number: "))
my_solution = Solution()
print(f"This number is a Disarium Number: {my_solution.is_disarium(number)}")

This number is a Disarium Number: True


### Write a Python program to print all happy numbers between 1 and 100 [1]

In [68]:
class Solution(object):
    def is_happy(self, num):
        """
        :num: int
        """

        if num < 0:
            raise(ValueError(f"Number should be greater than 0 and not {num}"))
        
        seen_numbers = set()

        while num != 1 and num not in seen_numbers:
            seen_numbers.add(num)
            str_num = str(num)
            num = 0
            for digit in str_num:
                num += pow(int(digit),2)
        return num == 1
    
    def happy_seq(self, min, max):
        happy_nums = []
        for i in range(min, max):
            if self.is_happy(i):
                happy_nums.append(i)
        return happy_nums
    
lower = int(input("Enter a lower number: "))
upper = int(input("Enter a upper number: "))
my_solution = Solution()
print(f"These are happy numbers from {lower} to {upper}: {my_solution.happy_seq(lower, upper)}")

These are happy numbers from 0 to 100: [1, 7, 10, 13, 19, 23, 28, 31, 32, 44, 49, 68, 70, 79, 82, 86, 91, 94, 97]


### Write a Python program to determine whether the given number is a Harshad Number [1]

In [77]:
class Solution(object):
    def is_harshad(self, num):
        """
        :num: int
        """

        if num < 0:
            raise(ValueError(f"Number should be greater than 0 and not {num}"))

        str_num = str(num)
        digits_sum = 0
        for digit in str_num:
            digits_sum += int(digit)
        return num % digits_sum == 0
    
number = int(input("Enter a number: "))
my_solution = Solution()
print(f"This number is a Harshad Number: {my_solution.is_harshad(number)}")

This number is a Harshad Number: True


### Write a Python program to find second largest number in a list [1]

In [4]:
class Solution(object):
    def second_max(self, nums):
        """
        :nums: List[int]
        """

        if len(nums) <= 1:
            raise(ValueError(f"List of integers is less than 1 element!"))

        nums.sort()

        return nums[-2]
    
numbers = [32,44,6,4,22,66]
my_solution = Solution()
print(f"The second max number is: {my_solution.second_max(numbers)}")

The second max number is: 44


### Write a Python program to find N largest elements from a list [1]

In [11]:
class Solution(object):
    def second_max(self, nums, lim):
        """
        :nums: List[int]
        :lim: int
        """

        if len(nums) <= lim-1:
            raise(ValueError(f"List of integers is less than 1 element!"))

        nums.sort()

        return nums[-lim:]
    
numbers = [32,44,6,4,22,66]
limit = 3
my_solution = Solution()
print(f"The {limit} max numbers are: {my_solution.second_max(numbers, limit)}")

The 3 max numbers are: [32, 44, 66]


### Write a Python program to Remove empty List from List [1]

In [22]:
class Solution(object):
    def remove_empty_lists(self, ls):
        """
        :ls: List[List]
        """

        if len(ls) < 1:
            raise(ValueError(f"List is empty!"))

        ls_no_empty = []
        for i in range(len(ls)):
            if len(ls[i]) > 0:
                ls_no_empty.append(ls[i])
        return ls_no_empty
    
        # Easier solution with list comprehension
        #return [ls_no_empty for ls_no_empty in ls if len(ls_no_empty) > 0]
    
lists = [[32,44], [], [6,4,22],[66], []]
my_solution = Solution()
print(f"The List without empty lists:\n{my_solution.remove_empty_lists(lists)}")

The List without empty lists:
[[32, 44], [6, 4, 22], [66]]


### Write a Python program to Count occurrences of an element in a list [1]

In [ ]:
class Solution(object):
    def count_occurrences(self, l, num):
        """
        :l: List[int]
        :num: int
        """

        if len(l) < 1:
            raise(ValueError(f"List is empty!"))
        
        return l.count(num)

        
    
_list = [1, 2, 3, 4, 2, 5, 2, 3, 4, 6, 5]
number = 4
my_solution = Solution()
print(f"The of occurances for {number} in the list is: {my_solution.count_occurrences(_list, number)}")

The of occurances for 4 in the list is: 2


### Write a Python program for removing 𝑖-𝑡ℎ character from a string [1]

In [ ]:
class Solution(object):
    def del_character(self, s, num):
        """
        :s: string
        :num: int
        """

        if len(s) <= 0 or len(s) <= num:
            raise(ValueError(f"String with wrong length: {len(s)}"))
        
        return s[:num] + s[num+1:]

        
     
string_before = str(input("Enter a string: "))
position = 4
my_solution = Solution()
print(f"The string before removing {position}-th element: {string_before}")
print(f"The string after removing {position}-th element: {my_solution.del_character(string_before, position)}")

The string before removing 4-th element: Hi, Mmy name is Silvano!!
The string after removing 4-th element: Hi, my name is Silvano!!


### Write a Python program to check if a given string is binary string or not [1]

In [ ]:
class Solution(object):
    def is_string_binary(self, s):
        """
        :s: string
        """

        if len(s) <= 0:
            raise(ValueError(f"String with wrong length: {len(s)}"))
        
        for c in s:
            if c not in "01":
                return False
        return True
     
_string = str(input("Enter a string: "))
my_solution = Solution()
print(f"The string {_string} is binary: {my_solution.is_string_binary(_string)}")

The string 010101010f is binary: False


### Write a Python program to find all duplicate characters in string [1]

In [ ]:
class Solution(object):
    def find_duplicates(self, s):
        """
        :s: string
        """

        if len(s) <= 0:
            raise(ValueError(f"Strings with wrong length: {len(s)}"))
        
        duplicates = []

        for (i,c)in enumerate(s):
            if c in s[i+1:]:
                duplicates.append(c)

        return set(duplicates)


string_ = str(input("Enter a string: "))
my_solution = Solution()
print(f"String: {string_}")
print(f"The duplicates are: {my_solution.find_duplicates(string_)}")

String: Hi, my name is Silvano
The duplicates are: {'m', 'n', ' ', 'a', 'i'}


### Write a Python Program to check if a string contains any special character [1]

In [ ]:
# Solution 1 - for loop

class Solution(object):
    def is_special_char(self, s):
        """
        :s: string
        """

        if len(s) <= 0:
            raise(ValueError(f"Strings with wrong length: {len(s)}"))
        
        specials = r'[!@#$%^&*()_+{}\[\]:;<>,.?~\\\/\'"\-=]'
        
        for c in s:
            if c in specials:
                return True
        
        return False


string_ = str(input("Enter a string: "))
my_solution = Solution()
print(f"String: {string_}")
print(f"The string contains special characters: {my_solution.is_special_char(string_)}")

String: Hi, my name is Silvano!!
The string contains special characters: True


In [ ]:
# Solution 2 - regular expression

import re

class Solution(object):
    def is_special_char(self, s):
        """
        :s: string
        """

        if len(s) <= 0:
            raise(ValueError(f"Strings with wrong length: {len(s)}"))
        
        specials = r'[!@#$%^&*()_+{}\[\]:;<>,.?~\\\/\'"\-=]'
        
        return True if re.search(specials, s) else False


string_ = str(input("Enter a string: "))
my_solution = Solution()
print(f"String: {string_}")
print(f"The string contains special characters: {my_solution.is_special_char(string_)}")

String: Hi, my name is Silvano!!
The string contains special characters: True


### Write a Python program to Extract Unique dictionary values [1]

In [ ]:
class Solution(object):
    def unique_val(self, d):
        """
        :d: Dict
        """

        if len(d) <= 0:
            raise(ValueError(f"Dict with wrong dimension: {len(d)}"))
        
        unique_values = []
        for k,v in d.items():
            unique_values.append(v)
        return list(set(unique_values))


my_dict = {
'a': 10,
'b': 20,
'c': 10,
'd': 30,
'e': 20
}
my_solution = Solution()
print(f"The unique values in the dict are: {my_solution.unique_val(my_dict)}")

The unique values in the dict are: [10, 20, 30]


### Write a Python program to Merging two Dictionaries [1]

In [53]:
class Solution(object):
    def merge_dict(self, d_1, d_2):
        """
        :d_1: Dict
        :d_2: Dict
        """

        if len(d_1) <= 0 or len(d_2)<=0:
            raise(ValueError(f"Dicts with wrong dimensions: {len(d_1)}, {len(d_2)}"))
        
        d_1.update(d_2)

        return d_1


my_dict_1 = {
'a': 10,
'b': 20,
'c': 10,
'd': 30,
'e': 20
}
my_dict_2 = {
'f': 10,
'g': 20,
'h': 10,
'i': 30,
'l': 20
}

my_solution = Solution()
print(f"The merged dict: \n{my_solution.merge_dict(my_dict_1, my_dict_2)}")

The merged dict: 
{'a': 10, 'b': 20, 'c': 10, 'd': 30, 'e': 20, 'f': 10, 'g': 20, 'h': 10, 'i': 30, 'l': 20}


### Write a Python program to convert key-values list to flat dictionary [1]

In [56]:
class Solution(object):
    def create_dict(self, l):
        """
        :l: List
        """

        if len(l) <= 0:
            raise(ValueError(f"List with wrong dimension: {len(l)}"))

        # Easy solution
        #return dict(l)
        
        new_dict = {}
        for keys, values in l:
            new_dict[keys] = values
        return new_dict
     


list_k_v = [('a', 1), ('b', 2), ('c', 3), ('d', 4)]

my_solution = Solution()
print(f"The dict from list of keys and values: \n{my_solution.create_dict(list_k_v)}")

The dict from list of keys and values: 
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


### Write a Python program to insertion at the beginning in OrderedDict [1]

In [16]:
from collections import OrderedDict

class Solution(object):
    def insert_first(self, ord_dict, new):
        """
        :ord_dict: OrderedDict
        :new: set
        """

        if len(ord_dict) <= 0:
            raise(ValueError(f"List with wrong dimension: {len(ord_dict)}"))

        new_ordered_item = OrderedDict([new])

        new_ordered_item.update(ord_dict)

        return new_ordered_item
        

ordered_dict = OrderedDict([('e', 5), ('b', 2), ('c', 3), ('d', 4)])
new_item = ('a', 1)

my_solution = Solution()
print(f"The OrderedDict with new first element: \n{my_solution.insert_first(ordered_dict, new_item)}")

The OrderedDict with new first element: 
OrderedDict([('a', 1), ('e', 5), ('b', 2), ('c', 3), ('d', 4)])


### Write a Python program to sort Python Dictionaries by Key or Value [1]

In [20]:
class Solution(object):
    def order_dict_by_key(self, d):
        """
        :d: Dict
        """

        if len(d) <= 0:
            raise(ValueError(f"List with wrong dimension: {len(d)}"))

        return dict(sorted(d.items()))
        

sample_dict = {'banana': 3, 'apple': 1, 'cherry': 2, 'date': 4}

my_solution = Solution()
print(f"Sorted dict by keys: \n{my_solution.order_dict_by_key(sample_dict)}")

Sorted dict by keys: 
{'apple': 1, 'banana': 3, 'cherry': 2, 'date': 4}


### Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j [1]

In [5]:
class Solution(object):
    def prod_ij(self, num_1, num_2):
        """
        :num_1: int
        :num_2: int
        """

        if num_1 <= 0 or num_2 <= 0:
            raise(ValueError(f"Numbers should be positive arrays greater than 0: {num_1}, {num_2}"))
        
        return [[i*j for i in range(num_2)] for j in range(num_1)]


     
rows = int(input("Enter a number: "))
colums = int(input("Enter a number: "))
my_solution = Solution()
print(f"The array with product i*j using these numbers {rows}, {colums}: \n{my_solution.prod_ij(rows, colums)}")

The array with product i*j using these numbers 5, 5: 
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8], [0, 3, 6, 9, 12], [0, 4, 8, 12, 16]]


### Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically [1]

In [ ]:
class Solution(object):
    def remove_dup_and_sort(self, s):
        """
        :s: string
        """

        if len(s) <= 0:
            raise(ValueError(f"String is empty: {len(s)}"))
        
        return " ".join(sorted(set(s.split())))


     
string_ = input("Enter a string: ")
my_solution = Solution()
print(f"String before removing duplicates and sorting it: {string_}")
print(f"String after removing duplicates and sorting it: {my_solution.remove_dup_and_sort(string_)}")

String before removing duplicates and sorting it: hi my name name is silvano quarto and this is my first name
String after removing duplicates and sorting it: and first hi is my name quarto silvano this


### Write a program that accepts a sentence and calculate the number of letters and digits [1]

In [21]:
class Solution(object):
    def count_digits_letters(self, s):
        """
        :s: string
        """

        if len(s) <= 0:
            raise(ValueError(f"String is empty: {len(s)}"))
        
        return len([i+1 for i in range(len(s)) if s[i].isalpha()]), len([j+1 for j in range(len(s)) if s[j].isdigit()])

     
string_ = input("Enter a string: ")
my_solution = Solution()
print(f"String: {string_}")
letters, digits = my_solution.count_digits_letters(string_)
print(f"Number of letters: {letters} \nNumber of digits: {digits}")

String: Ciao, sono Silvano e ho 30 anni
Number of letters: 22 
Number of digits: 2


### Write a program to compute the frequency of the words from the input. The output should output after sorting the key alphanumerically [1]

In [12]:
import re

class Solution(object):
    def word_freq(self, s):
        """
        :s: string
        """

        if len(s) <= 0:
            raise(ValueError(f"String is empty: {len(s)}"))
        
        cleaned_s = re.sub(r'[^a-zA-Z0-9 ]', '', s)

        set_words = set(cleaned_s.split(' '))
        dict_words_count = {}

        for word in set_words:
            dict_words_count[word] = cleaned_s.count(word)

        return sorted(dict_words_count.items())
        
string_ = input("Enter a string: ")
my_solution = Solution()
print(f"String: {string_}")
sorted_words_count = my_solution.word_freq(string_)
for key, value in sorted_words_count:
    print(f"{key}: {value}")

String: New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3.
2: 2
3: 2
New: 1
Python: 5
Read: 1
and: 1
between: 1
choosing: 1
or: 2
to: 1


### Define a class Person and its two child classes: Male and Female. All classes have a method "getGender" which can print "Male" for Male class and "Female" for Female class [1]

In [13]:
class Person:
    def GetGender(self):
        return "Unknown"

class Male(Person):
    def GetGender(self):
        return "Male"
    
class Female(Person):
    def GetGender(self):
        return "Female"
    
person = Person()
male = Male()
female = Female()
print(person.GetGender())
print(male.GetGender())
print(female.GetGender())

Unknown
Male
Female


### Define a class named Shape and its subclass Square. The Square class has an init function which takes a length as argument. Both classes have an area function which can print the area of the shape where Shape's area is 0 by default [1] 

In [4]:
class Shape:
    def __init__(self):
        pass

    def area(self):
        return 0

class Square(Shape):
    def __init__(self, length):
        super().__init__()
        self.length = length

    def area(self):
        return self.length*self.length

    
shape = Shape()
length_square = float(input("Enter the length of the square: "))
square = Square(length=length_square)
print(f"Area of Shape by default: {shape.area()}")
print(f"Area of Square with length {length_square}: {square.area()}")

Area of Shape by default: 0
Area of Square with length 2.5: 6.25


### Create a function that takes an angle in radians and returns the corresponding angle in degrees rounded to one decimal place [1]

In [8]:
import math

class Solution():
    def radians_to_degrees(self, rad):

        return round((rad * 360 / (2 * math.pi)), 1)
    
radians = float(input("Enter an angle: "))
my_solution = Solution()
print(f"The radian {radians} in degree is: {my_solution.radians_to_degrees(radians)}")

The radian 3.14 in degree is: 179.9


### In this challenge, establish if a given integer num is a Curzon number. If 1 plus 2 elevated to num is exactly divisible by 1 plus 2 multiplied by num, then num is a Curzon number [1]

Given a non-negative integer num, implement a function that returns True if num is a
Curzon number, or False otherwise

In [21]:
class Solution():
    def is_curzon(self, num):
        """
        :num: int
        """
        if num <= 0:
            raise ValueError(f"Your number {num} should be positive!")
        
        return (1 + 2**num) % (1 + 2*num) == 0
    
number = int(input("Enter a positive integer: "))
my_solution = Solution()
if my_solution.is_curzon(number):
    print(f"This number {number} is a Curzon number!")
else:
    print(f"This number {number} is NOT a Curzon number!")

This number 14 is a Curzon number!


### Create a function that replaces all the vowels in a string with a specified character [1]

In [16]:
class Solution():
    def replace_vowels(self, s):
        """
        :s: string
        """
        if len(s) == 0:
            raise ValueError(f"Your string {s} should not be empty!")
        
        vowels = ["a", "e", "i", "o", "u", "y"]
        for vowel in vowels:
            if vowel in s:
                s = s.replace(vowel, "#")
        return s
    
string_ = input("Enter a string: ")
my_solution = Solution()
print(f"Your string is: {string_}")
print(f"Your string replacing vowels with character # is: {my_solution.replace_vowels(string_)}")

Your string is: Hi, my name is Silvano
Your string replacing vowels with character # is: H#, m# n#m# #s S#lv#n#


### Write a function that calculates the factorial of a number recursively [1]

In [17]:
class Solution():
    def recursive_factorial(self, num):
        """
        :num: int
        """
        if num < 0:
            raise ValueError(f"Your number {num} should be greater than 0")
        
        if num == 0:
            return 1
        return num * self.recursive_factorial(num-1)
        
    
number = int(input("Enter a number: "))
my_solution = Solution()
print(f"The factorial of {number} is: {my_solution.recursive_factorial(number)}")

The factorial of 5 is: 120


### Hamming distance is the number of characters that differ between two strings [1]

To illustrate:
String1: "abcbba"
String2: "abcbda"
Hamming Distance: 1 - "b" vs. "d" is the only difference.

In [19]:
class Solution():
    def hamming_distance(self, s_1, s_2):
        """
        :s_1: string
        :s_2: string
        """
        if len(s_1) != len(s_2):
            raise ValueError("Input strings must have the same length!")
        
        h_distance = 0
        for i in range(len(s_1)):
            if s_1[i] != s_2[i]:
                h_distance += 1
        return h_distance
    
string_1 = input("Enter a string: ")
string_2 = input("Enter a second string: ")
my_solution = Solution()
print(f"First string is: {string_1}")
print(f"Second string is: {string_2}")
print(f"Hamming distance is: {my_solution.hamming_distance(string_1, string_2)}")

First string is: asdfghjkl
Second string is: asdfghnbm
Hamming distance is: 3


### Create a function that takes a list of non-negative integers and strings and return a new list without the strings [1]

In [3]:
class Solution():
    def only_numerical(self, l):
        """
        :l: list
        """
        if len(l) == 0:
            raise ValueError("Input list must has dimension greater than 0")
        
        new_list = []
        for element in l:
            if type(element) != str and element > 0:
                new_list.append(element)

        return new_list
    
list_ = [1, "ciao", 4, 3, "Silvano", -21]
my_solution = Solution()
print(f"List without strings and negative elements: {my_solution.only_numerical(list_)}")

List without strings and negative elements: [1, 4, 3]


### The "Reverser" takes a string as input and returns that string in reverse order, with the opposite case [1]

In [6]:
class Solution():
    def reverce_and_swap(self, s):
        """
        :s: string
        """
        if len(s) == 0:
            raise ValueError("Input string must has dimension greater than 0")
        
        return s[::-1].swapcase()
    
string_ = input("Enter a string: ")
my_solution = Solution()
print(f"Original string: {string_}")
print(f"String reversed and swapped: {my_solution.reverce_and_swap(string_)}")

Original string: Ciao, my name is Silvano Quarto
String reversed and swapped: OTRAUq ONAVLIs SI EMAN YM ,OAIc


### Write a function that moves all elements of one type to the end of the list [1]

In [5]:
class Solution():
    def move_element(self, l, elem):
        """
        :l: list
        :elem: object
        """
        if len(l) == 0:
            raise ValueError("Input list must has dimension greater than 0")
        
        new_list = [i for i in l if i != elem]
        new_list.extend([elem for _ in range(l.count(elem))])
        return new_list
    
list_ = [1,2,4,6,2,1,3,4,5,6,7,8,4,3]
number = 4
my_solution = Solution()
print(f"Moving all elements {number} at the end of the list: {my_solution.move_element(list_, number)}")

Moving all elements 4 at the end of the list: [1, 2, 6, 2, 1, 3, 5, 6, 7, 8, 3, 4, 4, 4]


### Create a function that reverses a boolean value and returns the string "boolean expected" if another variable type is given [1]

In [9]:
class Solution():
    def reverse_bool(self, value):
        """
        :value: bool
        """

        if isinstance(value, bool):
            return not value
        else:
            return "boolean expected"
            
val = False
my_solution = Solution()
print(f"The reversed boolean is: {my_solution.reverse_bool(val)}")

The reversed boolean is: True


### Create a function that takes a single string as argument and returns an ordered list containing the indices of all capital letters in the string [1]

In [11]:
class Solution():
    def capital_indexes(self, s):
        """
        :s: string
        """

        if len(s) == 0:
            raise ValueError("String dimension should be greater than 0")
        
        return [i for i, character in enumerate(s) if character.isupper()]

            
string_ = input("Enter a string: ")
my_solution = Solution()
print(f"Original string: {string_}")
print(f"The indexes of the capital letters: {my_solution.capital_indexes(string_)}")

Original string: Ciao sono Silvano Quarto
The indexes of the capital letters: [0, 10, 18]


### Given a list of numbers, create a function which returns the list but with each element's index in the list added to itself [1]
This means you add 0 to the number at index 0, add 1 to the number at index 1, etc...

In [ ]:
class Solution():
    def adding_indeces(self, l):
        """
        :l: List
        """

        if len(l) == 0:
            raise ValueError("List dimension should be greater than 0")
        
        return [i + num for i, num in enumerate(l)]

            
list_ = [1, 3, 5, 7, 9]
my_solution = Solution()
print(f"Original list: {list_}")
print(f"The list with added the indeces: {my_solution.adding_indeces(list_)}")

Original list: [1, 3, 5, 7, 9]
The list with added the indeces: [1, 4, 7, 10, 13]


### Create the function that takes a list of dictionaries and returns the sum of people's budgets [1]

In [ ]:
class Solution():
    def people_budget(self, people_dict):
        """
        :people_dict: Dict
        """

        return sum(person['budget'] for person in people_dict)
            
people = [
{'name': 'John', 'age': 21, 'budget': 23000},
{'name': 'Steve', 'age': 32, 'budget': 40000},
{'name': 'Martin', 'age': 16, 'budget': 2700}
]
my_solution = Solution()
print(f"The sum for each budget is: {my_solution.people_budget(people)}")

The sum for each budget is: 65700


### Create a function that takes a string and returns a string with its letters in alphabetical order [1]

In [9]:
class Solution():
    def alph_string(self, s):
        """
        :s: string
        """

        if len(s) == 0:
            raise ValueError("String dimension should be greater than 0")
        
        return "".join(sorted(s)).replace(" ", "")
        

string_ = input("Enter a string: ")
my_solution = Solution()
print(f"Original string: {string_}")
print(f"The string in alphabetic order is: {my_solution.alph_string(string_)}")

Original string: today is a good day
The string in alphabetic order is: aaadddgiooostyy


### Replicate Bubble Sort

In [12]:
class Solution():
    def bubble_sort(self, nums, mode = "increasing"):
        """
        :nums: List
        :mode: str
        """

        if len(nums) == 0:
            raise ValueError("List dimension should be greater than 0")
        
        for i in range(0, len(nums)):
            for j in range(0, len(nums) - i -1):
                if mode == "increasing":
                    if nums[j] > nums[j+1]:
                        nums[j], nums[j+1] = nums[j+1], nums[j]
                elif mode == 'decreasing':
                    if nums[j] < nums[j+1]:
                        nums[j], nums[j+1] = nums[j+1], nums[j]
                else:
                    raise ValueError(f"Modality is not {mode}, you can choose between increasing or decreasing!")

        return nums
        

list_ = [11,5,1,2,3,6,8,2,3,5,6,9,0]
modality = "decreasing"
my_solution = Solution()
print(f"Original list: {list_}")
print(f"List sorted with Bubble Sort: {my_solution.bubble_sort(list_, modality)}")

Original list: [11, 5, 1, 2, 3, 6, 8, 2, 3, 5, 6, 9, 0]
List sorted with Bubble Sort: [11, 9, 8, 6, 6, 5, 5, 3, 3, 2, 2, 1, 0]


### Create a function that takes a string and returns True or False, depending on whether the characters are in order or not [1]

In [14]:
class Solution():
    def is_ordered(self, s):
        """
        :s: str
        """

        if len(s) == 0:
            raise ValueError("String dimension should be greater than 0")
        
        return s == ''.join(sorted(s))
        

string_ = input("Enter a string: ")
my_solution = Solution()
print(f"Original string: {string_}")
print(f"This string is ordere?\n{my_solution.is_ordered(string_)}")

Original string: alpz
This string is ordere?
True


## Intermediate

### Write a Python program to find uncommon words from two Strings [1]

In [ ]:
class Solution(object):
    def uncommon_words(self, s_1, s_2):
        """
        :s_1: string
        :s_2: string
        """

        if len(s_1) < 0 or len(s_2) < 0:
            raise(ValueError(f"Strings with wrong length: {len(s_1)}, {len(s_2)}"))
        
        w_1 = set(s_1.split())
        w_2 = set(s_2.split())
        
        return list(w_1.symmetric_difference(w_2))
     
string_1 = str(input("Enter a string: "))
string_2 = str(input("Enter a string: "))
my_solution = Solution()
print(f"String 1: {string_1}")
print(f"String 2: {string_2}")
print(f"The uncommon words are: {my_solution.uncommon_words(string_1, string_2)}")

### From [1]

A website requires the users to input username and password to register. Write a
program to check the validity of password input by users. Following are the criteria
for checking the password:
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will
check them according to the above criteria. Passwords that match the criteria are to
be printed, each separated by a comma.

In [5]:
import re

class Solution():
    def validate_passwords(self, passwords):
        """
        :passwords: string
        """
        allowed_characters = {
        "lowercase": r"[a-z]",       
        "uppercase": r"[A-Z]",       
        "digit": r"[0-9]",          
        "special_char": r"[$#@]",    
        }
        
        list_passwords = passwords.split(",")
        valid_passwords = []

        for password in list_passwords:
            if (
                6 <= len(password) <= 12 and
                re.search(allowed_characters["lowercase"], password) and
                re.search(allowed_characters["uppercase"], password) and
                re.search(allowed_characters["digit"], password) and
                re.search(allowed_characters["special_char"], password)
            ):
                valid_passwords.append(password)

        return valid_passwords

string_passwords = input("Enter passwords separated by commas: ")
print(f"These are the possible passwords: {string_passwords}")
my_solution = Solution()
print(",".join(my_solution.validate_passwords(string_passwords)))

These are the possible passwords: ABd1234@1,a F1#,2w3E*,2We3345
ABd1234@1


### Please write a program to compress and decompress the string "hello world!hello world!hello world!hello world!" [1]

In [14]:
import zlib

class Solution():
    def compress_decompress_string(self, s):
        """
        :s: string
        """

        if len(s) <= 0:
            raise ValueError(f"String lenght is {len(s)}!")
        
        compressed_string = zlib.compress(s.encode())
        
        decompressed_string = zlib.decompress(compressed_string).decode()
        
        return compressed_string, decompressed_string

_string = input("Enter a string: ")
print(f"The string is: {_string}")
my_solution = Solution()
string_compressed, string_decompressed = my_solution.compress_decompress_string(_string)
print("Compressed String:", string_compressed)
print("Decompressed String:", string_decompressed)

The string is: hello world!hello world!hello world!hello world!
Compressed String: b'x\x9c\xcbH\xcd\xc9\xc9W(\xcf/\xcaIQ\xcc \x82\r\x00\xbd[\x11\xf5'
Decompressed String: hello world!hello world!hello world!hello world!


### Please write a binary search function which searches an item in a sorted list. The function should return the index of element to be searched in the list [1]

In [6]:
class Solution():
    def binary_search(self, l, t):
        """
        :l: List
        :t: int
        """

        left, right = 0, len(l) - 1

        while left <= right:

            middle = (left + right) // 2

            if l[middle] == t:
                return middle
            
            elif l[middle] < t:
                left = middle + 1

            else:
                right = middle - 1

        return -1

        

sorted_list = [1, 3, 5, 7, 9, 11, 13, 15]
target = 11
my_solution = Solution()
index = my_solution.binary_search(sorted_list, target)
if index != -1:
    print(f"Element {target} found at index {index}.")
else:
    print(f"Element {target} not found in the list.")

Element 11 found at index 5.


### Please write a program using generator to print the numbers which can be divisible by 5 and 7 between 0 and n [1]

In [14]:
class Solution():
    def is_divisible_by_5_and_7(self, num):
        """
        :num: int
        """

        if num <= 0:
            raise ValueError(f"Your number {num} should be greater than 0")

        for i in range(0,num+1):
            if i % 5 == 0 and i % 7 == 0:
                yield i

        

maximum = int(input("Enter a positive number: "))
print(f"Numbers divisible by 5 and 7 from 0 to {maximum}:")
my_solution = Solution()
for value in my_solution.is_divisible_by_5_and_7(maximum):
    print(value)

Numbers divisible by 5 and 7 from 0 to 100:
0
35
70


### Please write a program using generator to print the even numbers between 0 and n in comma separated form while n is input by console [1]

In [17]:
class Solution():
    def is_even(self, num):
        """
        :num: int
        """

        if num <= 0:
            raise ValueError(f"Your number {num} should be greater than 0")

        for i in range(1,num+1):
            if i % 2 == 0:
                yield i

    
maximum = int(input("Enter a positive number: "))
print(f"Even numbers from 0 to {maximum}:")
my_solution = Solution()
print(", ".join(map(str, my_solution.is_even(maximum))))

Even numbers from 0 to 25:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24


### From [1]

Assuming that we have some email addresses in the
"username@companyname.com (mailto:username@companyname.com)" format,
please write program to print the user name of a given email address. Both user
names and company names are composed of letters only.
Example:
If the following email address is given as input to the program:
john@google.com (mailto:john@google.com)
Then, the output of the program should be:
john

In [19]:
class Solution():
    def extract_username(self, e):
        """
        :e: string
        """

        if len(e) == 0:
            raise ValueError(f"Your email {e} is incorrect! Write your email")

        user = e.split("@")
        return user[0]
        
email = input("Enter your email: ")
print(f"Your email is: {email}:")
my_solution = Solution()
print(f"Your username is: {my_solution.extract_username(email)}")

Your email is: silvanoquarto@gmail.com:
Your username is: silvanoquarto


### Create a function that returns a base-2 (binary) representation of a base-10 (decimal) string number. To convert is simple: ((2) means base-2 and (10) means base-10) 010101001(2) = 1 + 8 + 32 + 128. [1]

In [7]:
class Solution():
    def binary_conversion(self, num):
        """
        :num: int
        """
        if num <= 0:
            raise ValueError(f"Your number {num} should be positive!")
        
        binary_repr = ""
        power = 0
        
        while num > 0:
            if num % 2 == 1:
                binary_repr = "1" + binary_repr
            else:
                binary_repr = "0" + binary_repr
            
            num //= 2
            power += 1

        return binary_repr
    
number = int(input("Enter a number: "), 10)
my_solution = Solution()
print(f"Binary representation of {number} is: {my_solution.binary_conversion(number)}")

Binary representation of 133 is: 10000101


## Advanced

# Pandas and Numpy Questions & Answers

These are some references about this topic:
- [1] [Numpy link](https://devinterview.io/questions/machine-learning-and-data-science/numpy-interview-questions/)
- [2] [Pandas link](https://devinterview.io/questions/machine-learning-and-data-science/pandas-interview-questions/)

In [1]:
import numpy as np

## Easy

### How do you create a NumPy array from a regular Python list? [1]

In [ ]:
class Solution(object):
    def list_to_array(self, l):
        """
        :l: List
        """

        if len(l) == 0:
            raise(ValueError(f"List with wrong length: {len(l)}"))
        
        return np.array(l)
     
list_ = [1,2,3,4,5,6,7]
my_solution = Solution()
print(f"This is the array: {my_solution.list_to_array(list_)}")
print(f"Array type is: {type(my_solution.list_to_array(list_))}")

This is the array: [1 2 3 4 5 6 7]
Array type is: <class 'numpy.ndarray'>


### How do you perform matrix multiplication using NumPy? [1]

In [14]:
class Solution(object):
    def multiply_matrix(self, mat_1, mat_2):
        """
        :mat_1: Matrix
        :mat_2: Matrix
        """

        if mat_1.shape[1] != mat_2.shape[0]:
            raise(ValueError(f"Incorrect shape for matrix: {mat_1.shape}, {mat_2.shape}"))
        
        return np.dot(mat_1, mat_2)
     
matrix_1 = np.array([[1,2], [3,4], [5,6]])
matrix_2 = np.array([[7,8,9], [10,11,12]])
my_solution = Solution()
print(f"The dot product is: \n{my_solution.multiply_matrix(matrix_1, matrix_2)}")

The dot product is: 
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


### How to invert a matrix? [1]

In [17]:
class Solution(object):
    def invert_matrix(self, mat):
        """
        :mat: Matrix 
        """
        if mat.shape[0] != mat.shape[1]:
            raise ValueError(f"Matrix must be square, but got shape: {mat.shape}")
        
        return np.linalg.inv(mat)

matrix = np.array([[2, 3], [1, 4]])
my_solution = Solution()
print(f"The inverse of the matrix is:\n{my_solution.invert_matrix(matrix)}")

The inverse of the matrix is:
[[ 0.8 -0.6]
 [-0.2  0.4]]


### How do you calculate the determinant of a matrix? [1]

In [20]:
class Solution(object):
    def det_matrix(self, mat):
        """
        :mat: Matrix 
        """
        if mat.shape[0] != mat.shape[1]:
            raise ValueError(f"Matrix must be square, but got shape: {mat.shape}")
        
        return round(np.linalg.det(mat), 2)

matrix = np.array([[2, 3], [1, 4]])
my_solution = Solution()
print(f"The determinant of the matrix is:\n{my_solution.det_matrix(matrix)}")

The determinant of the matrix is:
5.0


### How do you concatenate two arrays? [1]

In [10]:
class Solution(object):
    def concat_arrays(self, arr_1, arr_2, mode):
        """
        :arr_1: np.array 
        :arr_2: np.array 
        :mode: string 
        """
        if mode == 'vertically':
            #return np.concatenate((arr_1, arr_2), axis = 0)
            return np.vstack((arr_1, arr_2))
        elif mode == 'horizontally':
            #return np.concatenate((arr_1, arr_2), axis = 1)
            return np.hstack((arr_1, arr_2))
        else:
            raise ValueError(f"Choose a correct mode, not {mode}")

array_1 = np.array([[2, 3], [1, 4]])
array_2 = np.array([[6, 7], [8, 9]])
direction = "vertically"
my_solution = Solution()
print(f"The concatenated array is:\n{my_solution.concat_arrays(array_1, array_2, direction)}")

The concatenated array is:
[[2 3]
 [1 4]
 [6 7]
 [8 9]]


### How do you flat a multi dimensional array? [1]

In [ ]:
class Solution(object):
    def flat_array(self, arr):
        """
        :arr: np.array 
        """
        # for a memory-efficient solution
        #return arr.ravel()
        #return np.ravel(arr)

        return arr.reshape(-1)
    
        #return arr.flatten()

array_1 = np.array([[2, 3], [1, 4]])
my_solution = Solution()
print(f"The flatten array is:\n{my_solution.flat_array(array_1)}")

The flatten array is:
[2 3 1 4]


### How do you calculate the eigenvalues and eigenvectors of a matrix? [1]

In [20]:
class Solution(object):
    def eingen_vec_val(self, mat):
        """
        :mat: Matrix
        """
        return np.linalg.eig(mat)

matrix = np.array([[2, 3], [1, 4]])
my_solution = Solution()
eigen_val, eigen_vec = my_solution.eingen_vec_val(matrix)
print(f"The eigenvalues are:\n{eigen_val}")
print(f"The eigenvectors are:\n{eigen_vec}")

The eigenvalues are:
[1. 5.]
The eigenvectors are:
[[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]


### How can you reverse an array? [1]

In [3]:
class Solution(object):
    def reverse_array(self, arr):
        """
        :arr: array
        """
        return arr[::-1]

array = np.array([2, 3, 1, 4])
my_solution = Solution()
print(f"The reversed array is:\n{my_solution.reverse_array(array)}")

The reversed array is:
[4 1 3 2]


### How do you apply conditional filter to a NumPy array? [1]

In [4]:
array_test = np.array([1,2,3,4,5,6,7,8,9,10])

threshold = 4

print(f"Array with values greater than {threshold}: {array_test[array_test>threshold]}")

Array with values greater than 4: [ 5  6  7  8  9 10]


### How to normalize an array? [1]

In [13]:
array_test = np.array([1,2,3,4,5,6,7,8,9,10])

max = np.max(array_test)
min = np.min(array_test)

normalized_array = (array_test - min) / (max - min)

normalized_array

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### How can you compute percentiles with NumPy? [1]

In [19]:
array_test = np.array([1,2,3,4,5,6,7,8,9,10])

percentile = 90

print(f"The {percentile}-th percentile is: {np.percentile(array_test, percentile)}")

The 90-th percentile is: 9.1


### How to calculate Correlation Coefficient [1]

In [28]:
shape = (20,6)

features = np.random.rand(*shape)
#features = np.random.randn(*shape)
#features = np.random.randint(0,10, size = shape)
#features = 5 + (10-5) * np.random.rand(*shape)

np.corrcoef(features, rowvar=False)

array([[ 1.        , -0.22913281, -0.28013944,  0.03583473,  0.01016097,
        -0.09425893],
       [-0.22913281,  1.        ,  0.17345761, -0.16852136,  0.06883971,
         0.39088966],
       [-0.28013944,  0.17345761,  1.        , -0.24022698,  0.03237194,
         0.11412965],
       [ 0.03583473, -0.16852136, -0.24022698,  1.        , -0.0941801 ,
         0.25213887],
       [ 0.01016097,  0.06883971,  0.03237194, -0.0941801 ,  1.        ,
        -0.12436464],
       [-0.09425893,  0.39088966,  0.11412965,  0.25213887, -0.12436464,
         1.        ]])

### How to calculate Cumulative Sum? [1]

In [ ]:
array_test = np.array([1,2,3,4,5,6,7,8,9,10])

np.cumsum(array_test)

# cumulative product
# np.cumprod(array_test)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])